name: MS OFFICE 365 E5自动续期
on: 
  workflow_dispatch:
  schedule:
  - cron: '53 12 * * *'
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_TOKEN }}
    - name: 设置时区
      run: |
        sudo timedatectl set-timezone 'UTC'
    - name: 调用API
      env:
        CLIENT_ID1: ${{ secrets.CLIENT_ID1 }}
        CLIENT_SECRET1: ${{ secrets.CLIENT_SECRET1 }}
        REFESH_TOKEN1: ${{ secrets.REFESH_TOKEN1 }}
        CLIENT_ID2: ${{ secrets.CLIENT_ID2 }}
        CLIENT_SECRET2: ${{ secrets.CLIENT_SECRET2 }}
        REFESH_TOKEN2: ${{ secrets.REFESH_TOKEN2 }}
        # CLIENT_ID3: ${{ secrets.CLIENT_ID3 }}
        # CLIENT_SECRET3: ${{ secrets.CLIENT_SECRET3 }}
        # REFESH_TOKEN3: ${{ secrets.REFESH_TOKEN3 }}
      run: |
        ./graph_api_app.sh
    - name: 提交更改生效
      run: |
        git config --global user.email '<>'
        git config --global user.name ${GITHUB_ACTOR}  
        git pull
        git add .github/workflows/auto_ms_api.yml
        git add README.md
        git commit -m "schedule updated"
        git push -u origin master
